fastlane_version "1.46.1"

platform :ios do
                
        lane :beta do
            increment_build_number(
              xcodeproj: './ios/happycamper.xcodeproj'
            )

            sh("xctool -project ../ios/happycamper.xcodeproj -scheme happycamper clean archive -archivePath ../build/happycamper")

            sh("xcodebuild -exportArchive -exportFormat ipa -archivePath ../build/happycamper.xcarchive -exportPath ../build/happycamper.ipa -exportProvisioningProfile 'iOS Team Provisioning Profile: *'")        

            sh("cp ../build/happycamper.ipa $BITRISE_DEPLOY_DIR")
        end

end